version: "3"

services:
  api:
    build: .
    restart: always
    dns:
      - 1.1.1.1
      - 1.0.0.1
      - 8.8.8.8
    ports:
      - "80:80"

  db:
    image: mongo:6
    restart: always
    volumes:
      - ./data:/data/db
