version: "3"

services:
  api:
    image: exatom42/gump:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"

  db:
    image: mongo:6
    restart: always
    volumes:
      - ./data:/data/db
