version: "3"

services:
  api:
    build: exatom42/gump:latest
    restart: always
    dns:
      - 1.1.1.1
      - 1.0.0.1
      - 8.8.8.8
    ports:
      - "80:80"
      - "443:443"

  db:
    image: mongo:6
    restart: always
    volumes:
      - ./data:/data/db
